

# paths
dataset: 'Scannet200'
scene_id: 'scene0435_00'
root_dir: 'data/Scannet200/Scannet200_2D_5interval/val'
# scene_pcd_path: "/home/jie_zhenghao/Open3DIS/data/Scannet200/Scannet200_3D/val/original_ply_files/scene0435_00.ply"
scene_pcd_path: "data/Scannet200/Scannet200_3D/val/original_npy_files/scene0435_00.npy"
cam_pose_dir: "data/Scannet200/Scannet200_2D_5interval/val/scene0435_00/pose/"
depth_im_dir: "data/Scannet200/Scannet200_2D_5interval/val/scene0435_00/depth/"
mask_2d_dir: "output/mask_2d"

# grounding dino
ckpt_repo_id: "ShilongLiu/GroundingDINO"
ckpt_filename: "groundingdino_swinb_cogcoor.pth"
ckpt_config_filename: "GroundingDINO_SwinB.cfg.py"
dino_box_threshold: 0.4
dino_text_threshold: 0.4

# sam
sam_checkpoint: 'pretrained/sam_vit_h_4b8939.pth'
sam_url: 'https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth'

# prompt
base_prompt: "clothes"  #, Pillow, Chair, Sofa, Bed, Desk, Monitor, Television, Book"
