# paths
dataset: "Scannet200"
scene_id: "scene0435_00"

root_dir: "data/Scannet200/Scannet200_2D_5interval/val"
# scene_pcd_path: "/home/jie_zhenghao/Open3DIS/data/Scannet200/Scannet200_3D/val/original_ply_files/scene0435_00.ply"
scene_pcd_path: "data/Scannet200/Scannet200_3D/val/original_npy_files/scene0435_00.npy"
cam_pose_dir: "data/Scannet200/Scannet200_2D_5interval/val/scene0435_00/pose/"
depth_im_dir: "data/Scannet200/Scannet200_2D_5interval/val/scene0435_00/depth/"

stage_1_result_dir: "exp_stage_1/Result_OpenVocab_ISBNet-GSAM/final_result_hier_agglo/"

mask_2d_dir: "output/mask_2d"
mask_3d_dir: "output/mask_3d"

# rgb photo resolution
width_2d: 1296
height_2d: 968

# frames downsample ratio
downsample_ratio: 10 # pick 1 frame every `downsample_ratio` frames

# grounding dino
ckpt_repo_id: "ShilongLiu/GroundingDINO"
ckpt_filename: "groundingdino_swinb_cogcoor.pth"
ckpt_config_filename: "GroundingDINO_SwinB.cfg.py"
dino_box_threshold: 0.35
dino_text_threshold: 0.35

# sam
sam_checkpoint: "pretrained/sam_vit_h_4b8939.pth"
sam_url: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth"

# Aggregate
iou_thres: 0.3
similarity_thres: 0.75

# Filtering
if_occurance_threshold: False
occurance_threshold: 0.3 # points with occurance under lowest `occurance_threshold`% will be filtered out

if_detected_ratio_threshold: True
detected_ratio_threshold: 0.35 # points with detected ratio under lowest `detected_ratio_threshold`% will be filtered out

remove_filtered_masks: 0.5 # remove masks containing less than `remove_filtered_masks` percent points after filtering
remove_small_masks: 100 # 3d masks with less than `remove_small_masks` points will be removed

# prompt
base_prompt: "Clothes" #, Pillow, Chair, Sofa, Bed, Desk, Monitor, Television, Book"
